version: '3.6'
services:
  postgres:
    image: postgres:12
    restart: always
    ports:
      - 5430:5432
    environment:
      POSTGRES_PASSWORD: postgrespassword
  mssql:
    image: hasura/mssql-server-2019-cu10-ubuntu-20.04:latest
    restart: always
    ports:
      - 1430:1433
    environment:
      SA_PASSWORD: hasuraMSSQL1
  graphql-engine:
    image: hasura/graphql-engine:v2.0.0-beta.1
    ports:
      - '8085:8080'
    depends_on:
      - 'postgres'
    restart: always
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:postgrespassword@postgres:5432/postgres
      HASURA_GRAPHQL_ENABLE_CONSOLE: 'true' # set to "false" to disable console
