version: '3.6'
services:
  postgres:
    image: postgres:12
    restart: always
    ports:
      - 5430:5432
    environment:
      POSTGRES_PASSWORD: postgrespassword
  # DRIVER={ODBC Driver 17 for SQL Server};SERVER=msserver;Uid=SA;Pwd=testPassword123
  msserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - 1433:1433
    environment:
      SA_PASSWORD: "testPassword123"
      ACCEPT_EULA: "Y"
  graphql-engine:
    image: hasura/graphql-engine:v2.0.0-beta.1
    ports:
      - 8085:8080
    depends_on:
      - 'postgres'
    restart: always
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:postgrespassword@postgres:5432/postgres
      HASURA_GRAPHQL_ENABLE_CONSOLE: 'true' # set to "false" to disable console
